### ISSUE TITLE
How can I pass more than two points when I call directions on google maps?

### ISSUE THREAD

**Issue by AilsonFreire** [leanmotherfuckers/react-native-map-link#34]

**Comment by tschoffelen** [comment]
You mean as in multiple stops in directions? That is currently not supported in this library, but I would certainly welcome a PR for such functionality!

**Comment by AilsonFreire** [comment]
Oh, that's great invitation! Let me have some free time and I certainly will take this project to look if I can put more than two points

**Comment by tschoffelen** [comment]
Closing this one right now, since it's not really in the scope of this library, and since we're adding more and more app integrations, features like these will not be able to be implemented for every supported app.
