### ISSUE TITLE
open default map app with address as a string [country, street, house number]

### ISSUE THREAD

**Issue by b-asaf** [leanmotherfuckers/react-native-map-link#5]
Hi,
I am looking for a package that open the default map application of the user.
I saw this package and it seem nice, but I noticed it receive a location by latitude and longitude.
Is there a way to send the default map application the location as a string - for example:
`St foo 100, Bar` (bar is the country).

and this location/address string will be placed in the search box of the application?

**Comment by tschoffelen** [comment]
This is not currently built in, but shouldn't be too difficult to add.

Currently, the `latitude` and `longitude` parameteres are required, but if you could make those optional, and remove the `ll` parameters if those optional parameters are not specified, this script should do what you want.

I wholeheartedly welcome a PR 😄

**Comment by softov** [comment]
I have made some changes in the source to do that in google maps and apple maps. I don't figure out how to do that in uber or waze (they request latitude and longitude)

In showLocation(options)  I create this
`
export async function showLocation(options) {
  checkOptions(options)

  let useSourceDestiny = false
  let useDstAddr = false

  let sourceLat
  let sourceLng
  let sourceLatLng

  if (('sourceLatitude' in options) && ('sourceLongitude' in options)) {
    useSourceDestiny = true
    sourceLat = parseFloat(options.sourceLatitude)
    sourceLng = parseFloat(options.sourceLongitude)
    sourceLatLng = `${sourceLat},${sourceLng}`
  }

  if (('dstaddr' in options)) {
    useDstAddr = true
  }

  let dstaddr = options.dstaddr && options.dstaddr.length ? options.dstaddr : null
  let encodedDstaddr = dstaddr ? encodeURIComponent(dstaddr) : null
  let lat = parseFloat(options.latitude)
  let lng = parseFloat(options.longitude)
  let latlng = `${lat},${lng}`
  let title = options.title && options.title.length ? options.title : null
  let encodedTitle = encodeURIComponent(title)
  let app = options.app && options.app.length ? options.app : null
  let dialogTitle = options.dialogTitle && options.dialogTitle.length ? options.dialogTitle : 'Open in Maps'
  let dialogMessage = options.dialogMessage && options.dialogMessage.length ? options.dialogMessage : 'What app would you like to use?'
  let cancelText = options.cancelText && options.cancelText.length ? options.cancelText : 'Cancel'
  let appsWhiteList = options.appsWhiteList && options.appsWhiteList.length ? options.appsWhiteList : null

  if (!app) {
    app = await askAppChoice({
      dialogTitle,
      dialogMessage,
      cancelText,
      appsWhiteList
    })
  }

  let url = null

  switch (app) {
    case 'apple-maps':
      url = prefixes['apple-maps']
      url += `?q=${title ? encodedTitle : 'Location'}`
      url += (useDstAddr) ? `&daddr=${encodedDstaddr}` : `&daddr=${latlng}`
      url += (useSourceDestiny) ? `&saddr=${sourceLatLng}` : ''

      break
    case 'google-maps':
      let useTitleForQuery = !options.googleForceLatLon && title
      let googlePlaceId = options.googlePlaceId ? options.googlePlaceId : null

      url = prefixes['google-maps']
      url += `?q=${useTitleForQuery ? encodedTitle : latlng}`
      url += (isIOS) ? '&api=1' : ''
      url += (googlePlaceId) ? `&query_place_id=${googlePlaceId}` : ''

      url += (useSourceDestiny) ? `&saddr=${sourceLatLng}` : ''
      url += (useDstAddr) ? `&daddr=${encodedDstaddr}` : `&daddr=${latlng}`

      break
    case 'citymapper':
      ... same
      break
    case 'uber':
      url = `${prefixes['uber']}?action=setPickup`

      if (useDstAddr) {
        url += `&dropoff[formatted_address]=${encodedDstaddr}`
      } else {
        url += `&dropoff[latitude]=${lat}&dropoff[longitude]=${lng}`
      }
      
      url += (useSourceDestiny) ? `&pickup[latitude]=${sourceLat}&pickup[longitude]=${sourceLng}` : `&pickup=my_location`

      break
    case 'lyft':
      ... same
      break
    case 'waze':
      ... same
      break
    case 'yandex':
      ... same
      break
    case 'moovit':
      ... same
      break
  }

  if (url) {
    return Linking.openURL(url)
  }
}
`

Also need to change prefixes constants to uber and google open in iOS, (no tests in Android).

`
export const prefixes = {
  'apple-maps': isIOS ? 'http://maps.apple.com/' : 'applemaps://',
  'google-maps': !isIOS ? 'comgooglemaps://' : 'https://maps.google.com/',
  'citymapper': 'citymapper://',
  'uber': isIOS ? 'https://m.uber.com/ul/' : 'uber://',
  'lyft': 'lyft://',
  'transit': 'transit://',
  'waze': 'waze://',
  'yandex': 'yandexnavi://',
  'moovit': 'moovit://'
}
`

**Comment by tschoffelen** [comment]
Feel free to do a PR!

PR #42 already solves part of the original question for Apple Maps.

**Comment by tschoffelen** [comment]
Closing this one for now, since we like to keep the integrations work in a uniform manner, and not every one of the apps we support accepts a address as a parameter.
