### ISSUE TITLE
ios app proposal

### ISSUE THREAD

**Issue by abdelwehed** [leanmotherfuckers/react-native-map-link#73]
Hello,

I just used the library and it works fine on Android.
On IOS also it works but when the modal is open i only see apple maps in the app proposal even if i update info.plist file by adding the apps i want, i still dont get the proposal working.
N.B: tested on IOS 11 and 12  /  RN 0.58.3  
![Capture d’écran 2019-04-01 à 17 39 24](https://user-images.githubusercontent.com/20995060/55340532-2e9eb200-54a5-11e9-80e8-9b74f1619c1d.png)

**Comment by tschoffelen** [comment]
Hi @abdelwehed, thanks for using the library! Have you recompiled the app after updating your Info.plist file?

Also, if you're using Expo, please read this: https://github.com/leanmotherfuckers/react-native-map-link/blob/master/docs/expo.md

**Comment by abdelwehed** [comment]
Hi @tschoffelen, yes i recompiled my app after updating info.plist and i am not using expo.
Any one is having this issue ?

**Comment by tschoffelen** [comment]
Are you testing it on a real device or in the simulator?

**Comment by abdelwehed** [comment]
Real device of course :)

**Comment by tschoffelen** [comment]
Hmm, strange. Could you send me a copy of your Info.plist?

If you'd rather not do that publicly, feel free to email it to thomas@infowijs.nl

**Comment by abdelwehed** [comment]
Done ! i sent you email.

**Comment by lehresman** [comment]
Any movement on this?  I have the same problem.  I *am* using Expo, and I did follow the Expo instructions (adding LSApplicationQueriesSchemes), and recompiled.  Still I only see Apple Maps.

**Comment by tschoffelen** [comment]
Have you guys tried if the `showLocation` method (without the custom modal) yields the same results?

**Comment by lehresman** [comment]
Yes.  When I do this:

```
        await showLocation({
          title: contactAddress.addressLine,
          latitude: contactAddress.position.lat,
          longitude: contactAddress.position.lng,
        });
```

it loads Apple Maps directly without presenting any options.

I do have Google Maps installed on my phone.  I just confirmed that.

**Comment by abdelwehed** [comment]
Hello,

yes me too i tested showLocation but i had same behaviour like @lehresman

**Comment by tschoffelen** [comment]
I unfortunately can't produce this in any way...

Just tested it again by creating a new project using `react-native init MapTester`, updating `Info.plist`, running `yarn add react-native-map-link` and adding this to App.js:

```js
<TouchableOpacity onPress={() => {
  showLocation({
    latitude: 38.8976763,
    longitude: -77.0387185,
    title: 'The White House'
  })
}}><Text>Touch me</Text></TouchableOpacity>
```

This shows me all the options I would expect to show it on my phone (Apple Maps, Google Maps, Uber).

**Comment by abdelwehed** [comment]
It works for me now :).
In fact we had 4 plist files in the project and i had to add to all of them the 'LSApplicationQueriesSchemes'.
My bad and excuse me for my useless issue 😅
@lehresman try to see maybe you had the same pb; if yes close the issue.

**Comment by ysnfez** [comment]
@abdelwehed : Can you help me with ImagePicker.launchCamera issue.
![Head Office_1_MISC_May13_2019_photo1](https://user-images.githubusercontent.com/9275520/58195723-a1066400-7c96-11e9-81fc-ccfafeb667ba.jpg)
attached is image quality after uploading to windows server. thank you

**Comment by tschoffelen** [comment]
@ysnfez I don’t think this is really the place for that :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tschoffelen** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
