### ISSUE TITLE
Popup not working on Android.

### ISSUE THREAD

**Issue by gde-adi** [leanmotherfuckers/react-native-map-link#80]
Hi... I am newbie in React Native.
I follow this example https://github.com/leanmotherfuckers/react-native-map-link/blob/master/docs/popup.md

**Everything is working well on iOS, but not working on Android.**
What is wrong here ? (Please look my attachment file)

The logic is
I have a component named "OpenMapLocation". This component have 2 props, named 'address' and 'title'. Then with Geocoder (react-native-geocoding), I can get LatLong of the address.

[OpenMapLocation.js.txt](https://github.com/leanmotherfuckers/react-native-map-link/files/3161198/OpenMapLocation.js.txt)

Here the sample result on iOS
![Xnip2019-05-09_17-07-31](https://user-images.githubusercontent.com/18609378/57441831-51c73900-727d-11e9-9e15-f58bb22e3f59.jpg)

When I click the address, the popup will be displayed. It is working on iOS.
BUT NOT on Android.
Could you help me please? :)

**Comment by tschoffelen** [comment]
Hi! Are you getting any console errors?

**Comment by gde-adi** [comment]
Hi @tschoffelen thanks for you reply.

No, there is no any errors on console.
I have tried to do some trick that change the isVisible as TRUE.
`<Popup
isVisible={ true }
....`
It is working well. The Popup screen is displayed when load the main screen.

**Comment by gidox** [comment]
same problem :(

**Comment by amitbravo** [comment]
Mine is not working either on Android (device) or iOS (emulator ). no error found . it simply does not work. I tried a downgrade version too. didn't work either.

**Comment by amitbravo** [comment]
@gde-adi could you please a piece of code how its working on iOS , mine is not working

**Comment by gde-adi** [comment]
hi @amitbravo, I already put all my code on link above.

BUT, just let you know. Few days ago, I tried to reinstall my environment (because other issue), Unfortunately the Pop Up is not working on iOS and Android. 
So I assume that I think there is impact from other dependencies.

**Comment by SystemBlad** [comment]
Hi guys,
I had the same issue, I think it is a problem with other node-modules dependencies.
What I did to solve the problem is copy the source code library from node-modules and paste it inside my components. Hope this help to others.
