### ISSUE TITLE
Unable to resolve './constants'

### ISSUE THREAD

**Issue by jefffabiny** [leanmotherfuckers/react-native-map-link#82]
<img width="584" alt="Screen Shot 2019-05-21 at 9 56 15 PM" src="https://user-images.githubusercontent.com/1752323/58141982-60193b80-7c13-11e9-81ce-e598be4af611.png">

**Comment by tschoffelen** [comment]
Hi Jeff,

Could you try the following things for me:

1. Removing your `node_modules` directory and re-running `yarn` or `npm install`
2. Killing your packager, and restarting it with the `--reset-cache` flag?

I'm guessing there is something going wrong in the packager, not in the package itself.

**Comment by jefffabiny** [comment]
`rm -rf node_modules`
`npm install`
`expo r -c`

It's working. Thank you.
